Contexts domain
kirillovsky/stringconcat-carsharing pull request #6
Opened 2021-07-15 08:16 UTC by kirillovsky

Запилил домены контекстов.
Фикстурки для контекстов доменов вынесу в отдельные подмодули - _testFixtures_ когда буду пилить _usecase_ и _persistance_,
т.к. сейчас они нужны только в своих доменах.
А вот для _common-value-object_ уже вынес.
Фитнес-функции, правка userStory map и небольшие архиктурные косяки (не прикрепляются к билду отчеты для всех модулей кроме mainApp) пофикшу в следующих PR-ах

2021-07-19 08:59 UTC, elukianov requested changes

2021-07-19 08:59 UTC, elukianov commented on customer/domain/src/main/kotlin/com/stringconcat/kirillov/carsharing/customer/Customer.kt
> +    var status: CustomerStatus = REGISTERED
Тут я вижу уже небольшое расхождение с моделью. У нас клиент может быть либо Отклоненным, либо Зареганым. У нас ещё появляется статус Верифицированн и метод verify(). Потом придется остальным объяснять почему он нужен и где его место в модели

2021-07-19 08:59 UTC, elukianov commented on customer/domain/src/main/kotlin/com/stringconcat/kirillov/carsharing/customer/Customer.kt
> +private const val MATURITY_AGE = 21L
Я бы убрал это значение в интерфейс. Это выглядит как настройка параметра предметной области, очень вероятно, что может поменяться

2021-07-19 08:59 UTC, elukianov commented on customer/domain/src/main/kotlin/com/stringconcat/kirillov/carsharing/customer/Customer.kt
> +private fun isCustomerMatureEnough(customerBirthDate: LocalDate, clock: Clock): Boolean =
Честно говоря, ни разу не видел чтоб Clock использовали. Лучше наверное использовать дату

2021-07-19 08:59 UTC, elukianov commented on customer/domain/src/test/kotlin/com/stringconcat/kirillov/carsharing/customer/CustomerTest.kt
> +    fun `registerCustomer shouldn't create customer which not matured enough`() {
На будущее - registerCustomer выглядит как техническая подробность (в данном случае имя метода). Лучше просто описывать сценарий. Типа shouldn't register customer which not matured enough

2021-07-19 08:59 UTC, elukianov commented on customer/domain/src/test/kotlin/com/stringconcat/kirillov/carsharing/customer/DriverLicenseNumberTest.kt
> +    @Test
В таких случаях можно воспользоваться параметризоваными тестами, где в параметрах перечислить возможные варианты. По сути мы проверяем один и тот же кейс, но с разными данными, поэтому такое ок. У нас в примере есть как использовать такие тесты

2021-07-19 08:59 UTC, elukianov commented on customer/domain/src/test/kotlin/com/stringconcat/kirillov/carsharing/customer/Fixtures.kt
> +fun fullName(
Данные для тестов лучше делать рандомными

2021-07-19 08:59 UTC, elukianov commented on commons/value-objects/src/testFixtures/kotlin/com/stringconcat/kirillov/carsharing/commons/types/valueObjects/Fixtures.kt
> +        maker = "Camry"
Камри 3.5 обязательно =D

2021-07-19 08:59 UTC, elukianov commented on purchasing-department/domain/src/main/kotlin/com/stringconcat/kirillov/carsharing/purchasingDepartment/domain/PurchasingVehicle.kt
> +                id = idGenerator.generate(),
Косметическое замечание: когда много параметров в столбик, то лучше им имена таки проставлять

2021-07-19 08:59 UTC, elukianov commented on ride/domain/src/main/kotlin/com/stringconcat/kirillov/carsharing/ride/Ride.kt
> +    fun pay(price: Price): Either<Any, Unit> {
Тут понадобится ещё domain service, который будет расчитывать стоимость поездки. Этоо может быть отдельных класс, который потом в UseCase будет дергаться

2021-07-19 09:28 UTC, kirillovsky commented on customer/domain/src/main/kotlin/com/stringconcat/kirillov/carsharing/customer/Customer.kt
> +    var status: CustomerStatus = REGISTERED
Добавил сюда верификацию клиента, так как в поездке один из инвариантов создания поездки - это "Клиент проверен" и вроде бы про это говорили на эвент шторминге, но потом убрали эдействие проверки из контекста кастомера. Неоднозначность получается. Ну и к тому же, после отклонения нет возможности вернуть клиента в статус зарегистрирован

2021-07-19 09:29 UTC, kirillovsky commented on customer/domain/src/test/kotlin/com/stringconcat/kirillov/carsharing/customer/CustomerTest.kt
> +    fun `registerCustomer shouldn't create customer which not matured enough`() {
- [ ] поменять название теста  shouldn't register customer which not matured enough

2021-07-19 09:30 UTC, kirillovsky commented on customer/domain/src/test/kotlin/com/stringconcat/kirillov/carsharing/customer/DriverLicenseNumberTest.kt
> +    @Test
- [ ] use parametrized test instead

2021-07-19 09:35 UTC, kirillovsky commented on customer/domain/src/test/kotlin/com/stringconcat/kirillov/carsharing/customer/Fixtures.kt
> +fun fullName(
Да, как-то даже на это наступал. Не могли бы вы посоветовать библиотечку для генерации фейковых данных, может чем-нибудь таким пользовались.?

- [ ] make fixtures random

2021-07-19 09:37 UTC, kirillovsky commented on commons/value-objects/src/testFixtures/kotlin/com/stringconcat/kirillov/carsharing/commons/types/valueObjects/Fixtures.kt
> +        maker = "Camry"
Немножко не водитель я)) Поправлю) Там еще maker и name перепутаны

- [ ] swap name and maker here
- [ ] change model to Camry 3.5

2021-07-19 09:38 UTC, kirillovsky commented on purchasing-department/domain/src/main/kotlin/com/stringconcat/kirillov/carsharing/purchasingDepartment/domain/PurchasingVehicle.kt
> +                id = idGenerator.generate(),
Просто дублирование вида `name=name` получается. С другой стороны без нейминга параметров можно себе ногу отстрелить
- [ ] add names to multiple names

2021-07-19 09:40 UTC, kirillovsky commented on ride/domain/src/main/kotlin/com/stringconcat/kirillov/carsharing/ride/Ride.kt
> +    fun pay(price: Price): Either<Any, Unit> {
- [ ] move price  to use-case price provider

2021-07-19 09:43 UTC, kirillovsky commented on customer/domain/src/main/kotlin/com/stringconcat/kirillov/carsharing/customer/Customer.kt
> +private const val MATURITY_AGE = 21L
Согласен. Еще и сильно от законодательства зависит и типа транспортного средства (вроде бы)

- [ ] move to customer creation arguments

2021-07-19 09:48 UTC, kirillovsky commented on customer/domain/src/main/kotlin/com/stringconcat/kirillov/carsharing/customer/Customer.kt
> +private fun isCustomerMatureEnough(customerBirthDate: LocalDate, clock: Clock): Boolean =
Ну на работе у нас вроде народ активно это юзает. Но мб с датой и правда будет по проще, все таки Clock несколько геморойно создавать, ну и мб смотрится непривычно. Тут он использовался как эдакий date provider, только у clock возможностей по-больше.
Вы имеете ввиду текущую дату на момент проверки?
Остальные использования clock тоже заменить?

2021-07-19 09:49 UTC, kirillovsky commented on customer/domain/src/main/kotlin/com/stringconcat/kirillov/carsharing/customer/Customer.kt
> +private fun isCustomerMatureEnough(customerBirthDate: LocalDate, clock: Clock): Boolean =
- [ ] pass current date here

2021-07-19 20:02 UTC, kirillovsky commented on customer/domain/src/main/kotlin/com/stringconcat/kirillov/carsharing/customer/Customer.kt
> +    var status: CustomerStatus = REGISTERED
- [ ] remove registered status
- [ ] should create ride in context only if customer not rejected

2021-07-23 07:26 UTC, elukianov commented on customer/domain/src/main/kotlin/com/stringconcat/kirillov/carsharing/customer/Customer.kt
> +private fun isCustomerMatureEnough(customerBirthDate: LocalDate, clock: Clock): Boolean =
Да, можно везде поменять

2021-07-23 07:27 UTC, elukianov commented on customer/domain/src/test/kotlin/com/stringconcat/kirillov/carsharing/customer/Fixtures.kt
> +fun fullName(
Честно говоря вручную всё собираю, каких-то библиотек не юзал. Но вот вижу faker, надо будет тоже посмотреть)

2021-07-23 07:28 UTC, elukianov commented on purchasing-department/domain/src/main/kotlin/com/stringconcat/kirillov/carsharing/purchasingDepartment/domain/PurchasingVehicle.kt
> +                id = idGenerator.generate(),
А идея подсвечивает и это прям красиво выглядит, то что name = name это норм)

2021-07-23 07:32 UTC, elukianov commented on ride/domain/src/main/kotlin/com/stringconcat/kirillov/carsharing/ride/Ride.kt
> +    fun pay(price: Price): Either<Any, Unit> {
Его можно сразу же в домене и реализовать. Пока просто перемножить денежку на километр

2021-07-23 07:33 UTC, elukianov approved these changes
Там один комментарий про DomainService добавил, его реализовать и можно мержить

2021-07-23 08:00 UTC, kirillovsky commented on ride/domain/src/main/kotlin/com/stringconcat/kirillov/carsharing/ride/Ride.kt
> +    fun pay(price: Price): Either<Any, Unit> {
- [ ] implements here simplemle taximiter service

2021-07-23 19:07 UTC, merged